version: '3.2'

services:

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql

  frontend:
    build: frontend/
    ports:
      - 20080:80
    volumes:
      - ./:/app
    depends_on:
      - mysql

  backend:
    build: backend/
    ports:
      - 21080:80
    volumes:
      - ./:/app
    depends_on:
      - mysql
    #command: /usr/local/bin/php yii migrate --interactive 0
    #entrypoint: composer install
    